// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA350wUqBAVW2hjTSMdYmHhXDm6flFX3kU',
    appId: '1:932581831920:web:a7eecd14fa887ca4cf3e35',
    messagingSenderId: '932581831920',
    projectId: 'talk-257e0',
    authDomain: 'talk-257e0.firebaseapp.com',
    storageBucket: 'talk-257e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU59jKZtbAVJ22S2kLM2XUy5kIB4Un6-s',
    appId: '1:932581831920:android:bdaeccaeac688368cf3e35',
    messagingSenderId: '932581831920',
    projectId: 'talk-257e0',
    storageBucket: 'talk-257e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsFIE5CfaFx16s9I84fx-xGApouoRRiQY',
    appId: '1:932581831920:ios:9b4e927ed4cce4a6cf3e35',
    messagingSenderId: '932581831920',
    projectId: 'talk-257e0',
    storageBucket: 'talk-257e0.firebasestorage.app',
    iosBundleId: 'com.example.talk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsFIE5CfaFx16s9I84fx-xGApouoRRiQY',
    appId: '1:932581831920:ios:9b4e927ed4cce4a6cf3e35',
    messagingSenderId: '932581831920',
    projectId: 'talk-257e0',
    storageBucket: 'talk-257e0.firebasestorage.app',
    iosBundleId: 'com.example.talk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA350wUqBAVW2hjTSMdYmHhXDm6flFX3kU',
    appId: '1:932581831920:web:17d799a8e9ebede6cf3e35',
    messagingSenderId: '932581831920',
    projectId: 'talk-257e0',
    authDomain: 'talk-257e0.firebaseapp.com',
    storageBucket: 'talk-257e0.firebasestorage.app',
  );
}
